---
notifications:
  email:
    - slyphon@gmail.com

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby

before_install:
  - sudo apt-get update
  - sudo apt-get install zookeeperd

bundler_args: --without development

