---
notifications:
  email:
    - slyphon@gmail.com

env:
  - SPAWN_ZOOKEEPER='true'

rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree

# jruby specs are too intesive for travis
#   - jruby-18mode
#   - jruby-19mode

bundler_args: --without development docs

