# This should kick us over to the docker system
sudo: false

notifications:
  email:
    - slyphon@gmail.com
    - eric@5stops.com

env:
  - SPAWN_ZOOKEEPER='true'

# pull in releaseops submodule
before_install:
  - gem update bundler
  - git submodule update --init --recursive

rvm:
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.6
  - 2.4.3
  - 2.5.0
matrix:
  allow_failures:
    - rvm: ree
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: 1.8.7
    - rvm: 2.5.0

# jruby specs are too intesive for travis
#   - jruby-18mode
#   - jruby-19mode

bundler_args: --without development docs coverage
